Jsinterop packaging
digitaltwinconsortium/DTDLParser pull request #20
Opened 2023-02-21 20:08 UTC by vishnureddy17

This PR implements the changes discussed in #18

2023-02-21 20:09 UTC, vishnureddy17 commented
Do we need a copyright/license header in the JS and TS files?

2023-02-21 20:10 UTC, vishnureddy17 reviewed
Do we need a copyright/license header in the JS and TS files?

2023-02-21 20:40 UTC, rido-min requested changes
I'd move the JSInterop project to the javascript folder
Not sure if we want to produce a former npm package

Why we need to update the scripts? build can be done with standard dotnet cli, and we are not planning to pack this project

2023-02-21 20:43 UTC, jrdouceur commented
> I'd move the JSInterop project to the javascript folder

It is dotnet code; shouldn't it go in the dotnet folder?

> Why we need to update the scripts? build can be done with standard dotnet cli, and we are not planning to pack this project

no npm pack?

2023-02-21 21:02 UTC, jrdouceur commented on javascript/generated/DtdlOm.d.ts
> +  contents: { [name: string]: EntityType | string };
I had thought you were going to make this declaration in some other file; this is not really accurate for the JSON model exposed from the ParseToJson() method of the .NET parser.

2023-02-21 21:47 UTC, rido-min commented
> It is dotnet code; shouldn't it go in the dotnet folder?
yes, but it's intended to use by JS.. as it is including files from the js folder I think it belongs to that folder.

> no npm pack?
AFAIK we have not decided if we will publish this to NPM

2023-02-21 21:52 UTC, jrdouceur commented
> > yes, but it's intended to use by JS.. as it is including files from the js folder I think it belongs to that folder.
> 
> > AFAIK we have not decided if we will publish this to NPM

Vishnu, you will not be able to make some of these changes from a fork.  I will start a new PR that copies from this one and makes the changes Rido proposes: moving JSInterop and removing the packing.  I should have a chance to get to this later in the afternoon.

2023-02-21 21:53 UTC, vishnureddy17 commented on javascript/generated/DtdlOm.d.ts
> +  contents: { [name: string]: EntityType | string };
You're right. Will fix

2023-02-21 21:56 UTC, vishnureddy17 commented
If we're not publishing to NPM, I think that makes a _stronger_ case for keeping the NPM pack. The NPM pack will create a local tarball, which one might want since they can't install it from an online NPM registry.

2023-02-21 22:01 UTC, vishnureddy17 commented on javascript/generated/DtdlOm.d.ts
> +  contents: { [name: string]: EntityType | string };
I'll wait for your PR first @jrdouceur

2023-02-22 00:54 UTC, jrdouceur commented
> If we're not publishing to NPM, I think that makes a _stronger_ case for keeping the NPM pack. The NPM pack will create a local tarball, which one might want since they can't install it from an online NPM registry.

@rido-min Any response to this?  I'm holding off on packing until this is resolved.  How do you envision the interop layer being consumed?

2023-02-22 02:14 UTC, rido-min commented
I'd start with a sample showing how to consume the ParseToJson API from WASM. Until we got more customer evidence I would not start the packaging.. (if anyone needs the tarball, the sample instructions will show them how to do it).

2023-02-22 06:22 UTC, rido-min requested changes
the typings are not resolved from the package

2023-02-22 06:22 UTC, rido-min commented on dotnet/src/JsInterop/JsInterop.csproj
> +    <WasmMainJSPath>..\..\..\javascript\index.js</WasmMainJSPath>
moving this csproj to the javascript folder will avoid including files from a parent directory

2023-02-22 06:22 UTC, rido-min commented on dotnet/src/JsInterop/JsInterop.csproj
> +    <WasmExtraFilesToDeploy Include="..\..\..\javascript\DtdlErr.d.ts" />
wondering if DtdlErr.d.ts should be in the generated folder as DtdlOm

2023-02-22 06:22 UTC, rido-min commented on javascript/index.d.ts
> +import { DtdlObjectModel } from "./generated/DtdlOm";
I dont see the generated folder in the produced package

2023-02-22 12:17 UTC, jrdouceur commented on dotnet/src/JsInterop/JsInterop.csproj
> +    <WasmExtraFilesToDeploy Include="..\..\..\javascript\DtdlErr.d.ts" />
DtdlErr.d.ts is not a generated file.  It is handwritten.

2023-02-22 12:18 UTC, jrdouceur commented on javascript/index.d.ts
> +import { DtdlObjectModel } from "./generated/DtdlOm";
I'm guessing this will be a non-issue once the packing is removed?

2023-02-22 12:26 UTC, jrdouceur commented on javascript/index.js
> +    } catch (modelParsingError) {
My knowledge of JS is weak, but is line 21 correct?  This is catching an exception into variable 'modelParsingError', which is then thrown below on line 29, after having its 'exceptionInfo' field set to the value of the 'message' field from a variable named 'error', which does not seem to be declared anywhere in this file.

2023-02-22 19:06 UTC, vishnureddy17 commented on javascript/index.d.ts
> +import { DtdlObjectModel } from "./generated/DtdlOm";
@rido-min Yep. My mistake.

2023-02-22 19:08 UTC, vishnureddy17 commented on javascript/index.js
> +    } catch (modelParsingError) {
Dumb mistake on my part. Good catch.

2023-02-23 12:19 UTC, jrdouceur commented
Superseded by PR #23

2023-02-23 12:19 UTC, closed without merging