Move JsInterop files to javascript folder
digitaltwinconsortium/DTDLParser pull request #23
Opened 2023-02-22 13:20 UTC by jrdouceur

2023-02-22 15:39 UTC, rido-min requested changes
We are not going to produce NPM packages (for now)
Move the JSInterop project to the samples folder with a different name
We dont need any additional scripts/pipelines 

Where are the .d.ts files?

2023-02-22 15:48 UTC, jrdouceur commented
> We are not going to produce NPM packages (for now)

Agreed.

> Move the JSInterop project to the samples folder with a different name

I need to think of a different name.  At present, 'samples' is really a collection of tutorials; perhaps I should rename it to 'tutorials' and leave the name 'samples' for a less structured collection of coding examples?

Are you suggesting moving the entire 'javascript' folder to under 'samples'?  Or are you proposing a split?  If so, what goes where?

> We dont need any additional scripts/pipelines

Are we not going to make sure this builds?  Even if it's just a sample?

> Where are the .d.ts files?

They are currently:

* javascript\DtdlErr.d.ts
* javascript\index.d.ts
* generated\DtdlOm.d.ts

Where do you think they should go?

2023-02-22 16:07 UTC, rido-min commented
Tutorials/Samples doesnt matter, I will keep those as samples that will be built with the samples.sln

I'll keep the .d.ts files in the javascript folder.

2023-02-22 16:30 UTC, jrdouceur commented
> Tutorials/Samples doesnt matter, I will keep those as samples that will be built with the samples.sln

The current samples.sln is a generated file.  I'm going to start a separate PR that moves the extant samples to 'tutorials'.  Then, I'll come back to this PR and use it as a first entry in a new 'samples' folder and solution.

2023-02-22 17:10 UTC, jrdouceur commented
> > Tutorials/Samples doesnt matter, I will keep those as samples that will be built with the samples.sln
> 
> The current samples.sln is a generated file. I'm going to start a separate PR that moves the extant samples to 'tutorials'. Then, I'll come back to this PR and use it as a first entry in a new 'samples' folder and solution.

Got a PR out for the sample-to-tutorial change:  https://github.com/digitaltwinconsortium/DTDLParser/pull/24

2023-02-22 18:54 UTC, rido-min reviewed
some nits,

basically remove package related items.. As this might require additional edits/updates I can take it from here, once it's merged.

2023-02-22 18:54 UTC, rido-min commented on samples/JsInterop/JsInterop.csproj
>    <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
do we need this TF_Build?

2023-02-22 18:54 UTC, rido-min commented on samples/JsInterop/JsInterop.csproj
>    <PropertyGroup>
I'd suggest to rename the project to DtdlParserJSInteropSample

2023-02-22 18:54 UTC, rido-min commented on samples/JsInterop/JsInterop.csproj
>      <PackageLicenseExpression>MIT</PackageLicenseExpression>
if we are not packaging we dont need this

2023-02-22 18:54 UTC, rido-min commented on samples/JsInterop/JsInterop.csproj
>      <PackageId>DTDLParserInterop</PackageId>
no packagaing, this is not needed

2023-02-22 18:54 UTC, rido-min commented on samples/JsInterop/JsInterop.csproj
>      <DocumentationFile>$(OutputPath)DTDLParserInterop.xml</DocumentationFile>
I dont think we neee code comments for a sample

2023-02-22 18:54 UTC, rido-min commented on samples/JsInterop/JsInterop.csproj
>      <None Remove="stylecop.json" />
I would not add stylecop (neither GlobalSuppressions) in this sample

2023-02-22 18:54 UTC, rido-min commented on samples/JsInterop/JsInterop.csproj
> +    <WasmExtraFilesToDeploy Include="package.json" />
we dont need package.json

2023-02-22 19:19 UTC, vishnureddy17 reviewed
LGTM besides the one error. I'm good with @rido-min's feedback as well.

2023-02-22 19:19 UTC, vishnureddy17 commented on samples/JsInterop/index.js
> +            modelParsingError.exceptionInfo = JSON.parse(error.message)
Caught by @jrdouceur in the previous PR
```suggestion
            modelParsingError.exceptionInfo = JSON.parse(modelParsingError.message)
```

2023-02-22 20:14 UTC, jrdouceur commented on samples/JsInterop/JsInterop.csproj
> +    <WasmExtraFilesToDeploy Include="..\..\javascript\DtdlErr.d.ts" />
Where do we do the copying?  Custom build step?

2023-02-23 03:04 UTC, rido-min approved these changes

2023-02-23 03:05 UTC, rido-min commented
@jrdouceur make sure to squash the commits when merging

2023-02-23 12:15 UTC, merged